import type { Event } from "./types"

export const eventsData: Event[] = [
  {
    id: 1,
    title: "End of Semester Party",
    category: "Social",
    description: "Come celebrate the end of the semester with music, food, and games!",
    date: "Dec 15, 2023",
    time: "8:00 PM",
    location: "The Quad",
    attendees: {
      current: 45,
      max: 100,
    },
    verified: true,
  },
  {
    id: 2,
    title: "Exam Prep Study Group",
    category: "Academic",
    description: "Join fellow students to study for the upcoming calculus exam.",
    date: "Dec 10, 2023",
    time: "3:00 PM",
    location: "Main Library",
    attendees: {
      current: 12,
      max: 20,
    },
    verified: true,
  },
  {
    id: 3,
    title: "Intramural Basketball Tournament",
    category: "Sports",
    description: "Sign up your team for the end-of-year basketball tournament!",
    date: "Dec 18, 2023",
    time: "2:00 PM",
    location: "Recreation Center",
    attendees: {
      current: 32,
      max: 50,
    },
    verified: true,
  },
  {
    id: 4,
    title: "Campus Art Exhibition",
    category: "Arts",
    description: "View artwork created by students throughout the semester.",
    date: "Dec 20, 2023",
    time: "5:00 PM",
    location: "Art Building",
    attendees: {
      current: 18,
      max: 75,
    },
    verified: true,
  },
  {
    id: 5,
    title: "Hackathon 2023",
    category: "Academic",
    description: "Build innovative projects in 24 hours with great prizes!",
    date: "Dec 8, 2023",
    time: "9:00 AM",
    location: "Engineering Building",
    attendees: {
      current: 85,
      max: 150,
    },
    verified: true,
  },
  {
    id: 6,
    title: "Movie Night: Finals Edition",
    category: "Social",
    description: "Take a break from studying with a screening of Ferris Bueller's Day Off.",
    date: "Dec 12, 2023",
    time: "7:30 PM",
    location: "Student Union",
    attendees: {
      current: 28,
      max: 75,
    },
    verified: true,
  },
]
